### ISSUE TITLE
cannot use interactive mode on macos with coreutils

### ISSUE THREAD

**Issue by takemikami** [imas/rdflint#137]
Interactive mode do not work on macos with coreutils, and display following error.

![E_6tbKBVQAE1fJ_](https://user-images.githubusercontent.com/1129652/137306999-b523346a-de85-42d0-86df-d5ea5fb2af9c.jpeg)

This problem will fix after merge the pull request https://github.com/jline/jline3/pull/706 .

**Comment by foooomio** [comment]
JLine 3.21.0 has been released that contains the fix for the issue.
