### ISSUE TITLE
Interactive Mode での DESCRIBE の実行

### ISSUE THREAD

**Issue by foooomio** [imas/rdflint#42]
https://github.com/imas/rdflint/blob/e5db74a38fe110823e5795766191bb9fef70e51c/src/main/java/com/github/imas/rdflint/RdfLint.java#L347-L353

[`QueryExecution#execSelect()`](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/QueryExecution.html#execSelect--) は DESCRIBE が実行できずにエラーが投げられます。 

[`Query#getQueryType()`](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/Query.html#getQueryType--) でクエリタイプを取得して分岐し、 [`QueryExecution#execDescribe()`](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/QueryExecution.html#execDescribe--) を実行するのがいいかと思います（返り値も異なります）。

**Comment by foooomio** [comment]
`QueryExecution#execDescribe()` すると `Model` が返りますが、`ResultSet` の `ResultSetFormatter` のようなものがないため、何らかの言語で出力することになります。出力の形式をどうするか、ご意見をうかがいたいです。

`Model` を出力するのには以下の方法があります。

- `Model#write(OutputStream, String)` で出力する言語を次の中から文字列で指定する。
  - "RDF/XML", "RDF/XML-ABBREV", "N-TRIPLE", "TURTLE", (and "TTL") and "N3"
- `RDFDataMgr#write(OutputStream, Model, RDFFormat)` で [`RDFFormat`](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/riot/RDFFormat.html) を指定する。

後者の方法で `RDFFormat` の `TURTLE_BLOCK` か `TURTLE_FLAT` か `TURTLE_PRETTY` を指定するのが見やすいと思うのですが、例として空白ノードのある URI で試してみると、こういうふうな出力になります。

```turtle
# TURTLE_BLOCK
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
        <http://purl.org/dc/terms/issued>  "2017-01-01" ;
        <http://purl.org/dc/terms/creator>  _:b0 ;
        <http://www.w3.org/2000/01/rdf-schema#label>  "imas-schema語彙"@ja ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://www.w3.org/2002/07/owl#Ontology> .

_:b0    <http://xmlns.com/foaf/0.1/name>  "crssnky"@ja ;
        <http://xmlns.com/foaf/0.1/homepage>  <https://sparql.crssnky.xyz/imas/> .


# TURTLE_FLAT
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#> <http://purl.org/dc/terms/issued> "2017-01-01" .
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#> <http://purl.org/dc/terms/creator> _:b0 .
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#> <http://www.w3.org/2000/01/rdf-schema#label> "imas-schema語彙"@ja .
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Ontology> .
_:b0 <http://xmlns.com/foaf/0.1/name> "crssnky"@ja .
_:b0 <http://xmlns.com/foaf/0.1/homepage> <https://sparql.crssnky.xyz/imas/> .


# TURTLE_PRETTY
<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
        a       <http://www.w3.org/2002/07/owl#Ontology> ;
        <http://www.w3.org/2000/01/rdf-schema#label>
                "imas-schema語彙"@ja ;
        <http://purl.org/dc/terms/creator>
                [ <http://xmlns.com/foaf/0.1/homepage>
                          <https://sparql.crssnky.xyz/imas/> ;
                  <http://xmlns.com/foaf/0.1/name>
                          "crssnky"@ja
                ] ;
        <http://purl.org/dc/terms/issued>
                "2017-01-01" .
```

この中では個人的に `TURTLE_BLOCK` が一番見やすいと思うのですが、いかがでしょうか？

**Comment by takemikami** [comment]
提案頂いた、RDFDataMgr#writeのTURTLE_BLOCKで良いかと思います
\# 将来的には、出力形式の切替機能を実装するのが理想的かもですが
