### ISSUE TITLE
Interactive Mode での BASE と PREFIX の省略機能？

### ISSUE THREAD

**Issue by foooomio** [imas/rdflint#43]
Interactive Mode で入力するクエリの BASE と PREFIX について、読み込んだ RDF ファイルに記述されているものを省略できる機能を提案します（筋が悪いでしょうか？）。

PREFIX については、 [`org.apache.jena.graph.Graph#getPrefixMapping()`](https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/graph/Graph.html#getPrefixMapping--) が使えるかもしれません。

**Comment by foooomio** [comment]
RDF 同士でコンフリクトしたときの問題がありました。たとえば、`A.ttl` で
```turtle
@prefix ex: <http://example.com/A#>
```
となっているところ、`B.ttl` で
```turtle
@prefix ex: <http://example.com/B#>
```
となっていた場合、どちらを優先すべきか、など。

config ファイルによく使う PREFIX を記述できるようにするアイデアもありますが。

**Comment by takemikami** [comment]
当初、Interactive Modeのクエリ機能は、
PullRequest上げる前の検証用という位置づけで考えていました。

当初、想定していた使い方:
1. im@sparqlのサイトでクエリを実行
2. 期待していたデータが無い
3. rdfを編集してデータを追加
4. 1のクエリをInteractiveModeにコピペして、追加されたデータを確認

が、Interactive Modeで（コピペでなく）クエリを書くことも多そうなので、
なんからの入力支援をする仕組みは、あった方が良いと思います。

クエリの入力に関しては、完全に省略するよりも、
タブキーなどで補完できる方が良いかなと考えていますがいかがでしょうか？
\# rdflint上でしか動かない(省略を前提とした)クエリを許すと、  
\# SPARQLを勉強している人などにとって、混乱の原因になりそうなので。

**Comment by foooomio** [comment]
> クエリの入力に関しては、完全に省略するよりも、
> タブキーなどで補完できる方が良いかなと考えていますがいかがでしょうか？

なるほど、その発想はなかったです。タブ補完良さそうに思います。
