### ISSUE TITLE
rdflint-problems.yml の出力先ディレクトリ指定

### ISSUE THREAD

**Issue by foooomio** [imas/rdflint#55]
rdflint-problems.yml の出力先ディレクトリを指定できる設定項目がほしいです。

**Comment by foooomio** [comment]
手元で以下のように動作する変更を加えました。

- `-outputdir` オプションがある場合
  - `rdflint-problems.yml` の出力先をそのパスに変更
- `-outputdir` オプションがない場合
  - `rdflint-config.yml` に `outputDir` の指定がある場合、そのパス
  - `-targetdir` または `targetDir` に指定がある場合、そのパス
  - 上記のいずれもない場合、カレントディレクトリ

こちらでよろしければプルリクを送りますが、オプション周りの仕様やテストを整えてからにしますか？

**Comment by takemikami** [comment]
大丈夫です、PR送って下さい。一旦取り込みます。
（今後、仕様を整理して変更するかもしれませんが）
