### ISSUE TITLE
SHACL制約の与え方について

### ISSUE THREAD

**Issue by yayamamo** [imas/rdflint#73]
初めまして。有益なツールの提供をどうもありがとうございます。
ところで、SHACL制約の与え方について、ドキュメントを読んだ限りでは分かりませんでしたので、追加していただけますか?

**Comment by kiridaruma** [comment]
@yayamamo issueありがとうございます
今ちょうど #74 にてreadmeに簡単な使い方を追加しようとしているんですが、その他に具体的にどのような情報がほしい等ありますか？

**Comment by yayamamo** [comment]
早速ありがとうございます。必要十分な内容だと思います。
